# Generated by Django 3.0.7 on 2020-09-13 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien', models.DateField(help_text='Dzień wizyty', verbose_name='Dzień wizyty')),
                ('godzina_start', models.TimeField(help_text='Godzina wityty', verbose_name='Godzina rozpoczęcia wizyty')),
                ('godzina_koniec', models.TimeField(help_text='Godzina zakończenia', verbose_name='Godzina zakończenia wizyty')),
                ('notatki', models.TextField(blank=True, help_text='Miejsce na Twoje notatki', verbose_name='Notatki')),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('plec', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='Jeśli jesteś kobitą wpis k, jeżeli mężczyzną wpisz m.', regex='k|m')])),
                ('numer_telefonu', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Proszę podać numer telefonu w formacie: +999999999.', regex='^\\+?1?\\d{9,15}$')])),
                ('data_utworzenia_konta', models.DateTimeField()),
                ('wizyta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Wizyta')),
            ],
        ),
    ]
