# Generated by Django 3.0.7 on 2020-09-20 13:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(blank=True, default=None, max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('rok_urodzenia', models.DateTimeField(blank=True, null=True, verbose_name='%Y')),
                ('plec', models.CharField(choices=[('K', 'k'), ('M', 'm')], max_length=1)),
                ('numer_telefonu', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Proszę podać numer telefonu w formacie: +999999999.', regex='^\\+?1?\\d{9,15}$')])),
                ('data_utworzenia_konta', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Dzień wizyty', verbose_name='Dzień wizyty')),
                ('start_time', models.TimeField(help_text='Godzina wityty', verbose_name='Godzina rozpoczęcia wizyty')),
                ('end_time', models.TimeField(help_text='Godzina zakończenia', verbose_name='Godzina zakończenia wizyty')),
                ('notes', models.TextField(blank=True, help_text='Miejsce na Twoje notatki', verbose_name='Notatki')),
                ('pacjent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.Pacjent')),
            ],
            options={
                'verbose_name': 'Kalendarz wizyt',
                'verbose_name_plural': 'Kalendarz wizyt',
            },
        ),
    ]
