# Generated by Django 3.0.7 on 2020-09-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'verbose_name': 'Scheduling', 'verbose_name_plural': 'Scheduling'},
        ),
        migrations.RenameField(
            model_name='wizyta',
            old_name='dzien',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='wizyta',
            old_name='godzina_koniec',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='wizyta',
            old_name='notatki',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='wizyta',
            old_name='godzina_start',
            new_name='start_time',
        ),
    ]
