# Generated by Django 3.0.7 on 2020-09-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20200913_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'verbose_name': 'Kalendarz wizyt', 'verbose_name_plural': 'Kalendarz wizyt'},
        ),
        migrations.RemoveField(
            model_name='pacjent',
            name='wizyta',
        ),
        migrations.AddField(
            model_name='wizyta',
            name='pacjent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.Pacjent'),
        ),
    ]
