# Generated by Django 3.0.7 on 2020-09-20 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0003_auto_20200920_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacjent',
            name='imie',
        ),
        migrations.AddField(
            model_name='pacjent',
            name='rok_urodzenia',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacjent',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
