# Generated by Django 3.0.7 on 2020-09-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20200920_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjent',
            name='imie',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='data_utworzenia_konta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='plec',
            field=models.CharField(choices=[('K', 'M'), ('k', 'm')], max_length=1),
        ),
    ]
